#Application Configuration
server:
  port: 8010
  servlet:
    context-path: /mhs-ordimag-ms

spring:
  profiles:
    active: dev

  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:as400://192.168.20.3;naming=system;libraries=his061223,interlabpr;prompt=false?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
    username: HOSVITAL
    password: HOSVITAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.DB2400Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/